In [38]:
#import pacakges 
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from PIL import Image
import math
import numpy
import cv2
from pylab import *
from numpy import *
from numpy import array
import random;
from scipy.interpolate import RectBivariateSpline

# Use Sift to get matching point 

In [614]:
!pip install opencv-python==3.4.2.16
!pip install opencv-contrib-python==3.4.2.16
#!pip install opencv-python
import cv2
from PIL import Image
import numpy as np
import random
import matplotlib.pyplot as plt
img1 = cv2.imread('./Images/image1.jpg')
img2 = cv2.imread('./Images/image2.jpg')

gray= cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
gray2= cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)


In [615]:
# Initiate SIFT detector
sift = cv2.xfeatures2d.SIFT_create()
kp1, src = sift.detectAndCompute(gray2,None)
kp2, dst = sift.detectAndCompute(gray,None)
print ("Found keypoints in image 2: " + str(len(kp1)))
print ("Found keypoints in image 1: " + str(len(kp2)))

Found keypoints in image 2: 4475
Found keypoints in image 1: 5741


In [397]:
bf = cv2.BFMatcher()
matches = bf.match(src, dst)
keypoints = [kp1,kp2]
correspondenceList = []
#matches = np.array(matches)
for match in matches:
            (x1, y1) = keypoints[0][match.queryIdx].pt
            (x2, y2) = keypoints[1][match.trainIdx].pt
            correspondenceList.append([x1, y1, x2, y2])

corrs = np.array((correspondenceList))
estimation_thresh = 0.6

# Use Ransac to get the best homography

In [359]:
def ransac(corr, thresh):
    maxInliers = []
    finalH = None
    randomFour = np.zeros((4,4)) 
    for i in range(500):
        #find 4 random points to calculate a homography
        point1 = corr[random.randrange(0, len(corr))]
        randomFour [0]=point1
        point2 = corr[random.randrange(0, len(corr))]
        randomFour [1]=point2
        point3 = corr[random.randrange(0, len(corr))]
        randomFour [2]=point3
        point4 = corr[random.randrange(0, len(corr))]
        randomFour [3]=point4

        #call the homography function on those points
        h = findHomography(randomFour)
        inliers = []
       
    #for every point in the corres
        for i in range(len(corr)):
            d = geometricDistance(corr[i], h)
            if d < 5:
                inliers.append(corr[i])

        if len(inliers) > len(maxInliers):
            maxInliers = inliers
            finalH = h
       # print ("size: ", len(corr), " NumInliers: ", len(inliers), "Max inliers: ", len(maxInliers))

        if len(maxInliers) > (len(corr)*thresh):
            break
    return finalH, maxInliers

In [329]:
def split_array(corr):
    x=[]
    y=[]
    xdash=[]
    ydash=[]
    b=[]
    for i in range(4):
        x.append(corr[i][0])
        y.append(corr[i][1])
        xdash.append(corr[i][2])
        ydash.append(corr[i][3])
        b.append(corr[i][2])
        b.append(corr[i][3])
    return x,y,xdash,ydash,b

In [330]:
def geometricDistance(correspondence, h):

    p1 = np.array([correspondence[0], correspondence[1], 1])
    estimatep2 = np.dot(h, p1)
    estimatep2 = (1/estimatep2.item(2))*estimatep2

    p2 = np.array([correspondence[2], correspondence[3], 1])
    error = p2 - estimatep2
    return np.linalg.norm(error)

In [652]:
def findHomography(corr):
   
    #b = dest.flatten().reshape(-1,1)
    x,y,xdash,ydash,b = split_array(corr)
    
    M = np.array([
          [x[0],y[0],1,0,0,0,-x[0]*xdash[0], -y[0]*xdash[0]],
          [0,0,0,x[0],y[0],1,-x[0]*ydash[0], -y[0]*ydash[0]],
          [x[1],y[1],1,0,0,0,-x[1]*xdash[1],-y[1]*xdash[1]],
          [0,0,0,x[1],y[1],1,-x[1]*ydash[1],-y[1]*ydash[1]],
          [x[2],y[2],1,0,0,0,-x[2]*xdash[2],-y[2]*xdash[2]],
          [0,0,0,x[2],y[2],1,-x[2]*ydash[2],-y[2]*ydash[2]],
          [x[3],y[3],1,0,0,0,-x[3]*xdash[3],-y[3]*xdash[3]],
          [0,0,0,x[3],y[3],1,-x[3]*ydash[3],-y[3]*ydash[3]]
      ])
    print(b)
    a = np.dot(np.linalg.inv(M),b)
    a = np.append(a,1)
    return a.reshape(3,3)

In [398]:
#Run the ransac
finalH, inliers = ransac(corrs, estimation_thresh)
print ("Final homography: ", finalH)
print ("Final inliers count: ", len(inliers))
h = np.array(finalH)

Final homography:  [[ 7.08991088e-01  6.41428142e-03  4.59588972e+02]
 [-1.55384384e-01  8.77791607e-01  8.62252041e+01]
 [-2.50254536e-04 -5.68269583e-05  1.00000000e+00]]
Final inliers count:  1163


# 1) Use ginput to find correspondances

In [639]:
def getPoints(image):
    img1 = Image.open(image) 
    plt.figure(1)
    plt.imshow(img1)
    print("Please click") 
    x = plt.ginput(4)
    return x

In [640]:
pts_src = getPoints('./Images/image1.jpg')
print(pts_src)
pts_dst=getPoints('./Images/image2.jpg')
print(pts_dst)
plt.close()

Please click


/usr/lib/python3/dist-packages/matplotlib/backend_bases.py:2437: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


[(780.7925483121329, 538.9831213307241), (885.2140258072405, 325.12793542074377), (1018.8735170009783, 330.9755381604698), (906.9336931262229, 539.818493150685)]
Please click
[(325.5149064334638, 505.5682485322897), (439.96084576810176, 300.0667808219179), (560.2543878424657, 318.44496086105687), (445.80844850782773, 510.5804794520549)]


In [653]:
corrs = np.concatenate((pts_dst,pts_src),axis=1)
corrs.shape

(4, 4)

In [648]:
#check sizes of image one and image 2
img2 = array(Image.open('./Images/image2.jpg'))
print(img2.shape)
img1 = array(Image.open('./Images/image1.jpg'))
print (img1.shape)

(683, 1024, 3)
(683, 1024, 3)


#

In [649]:
#get x,y,x',y' arrays from cores
def getArrays(src,dest):
    x=[]
    y=[]
    xdash=[]
    ydash=[]

    for i in range(4):
        x.append(src[i][0])
        y.append(src[i][1])
        xdash.append(dest[i][0])
        ydash.append(dest[i][1])

    return x,y,xdash,ydash

In [650]:
def split_array(corr):
    x=[]
    y=[]
    xdash=[]
    ydash=[]
    b=[]
    for i in range(4):
        x.append(corr[i][0])
        y.append(corr[i][1])
        xdash.append(corr[i][2])
        ydash.append(corr[i][3])
        b.append(corr[i][2])
        b.append(corr[i][3])
    return x,y,xdash,ydash,b

In [654]:
h=findHomography(corrs)
print("calculated homography", h)
h, status = cv2.findHomography(np.array(pts_dst),np.array(pts_src))
print("actual homogrpahy", h)

[780.7925483121329, 538.9831213307241, 885.2140258072405, 325.12793542074377, 1018.8735170009783, 330.9755381604698, 906.9336931262229, 539.818493150685]
calculated homography [[ 6.49538686e-01 -2.14323019e-02  4.72889222e+02]
 [-1.80357970e-01  8.17439342e-01  1.10348521e+02]
 [-2.78248097e-04 -9.26799936e-05  1.00000000e+00]]
actual homogrpahy [[ 6.49538139e-01 -2.14335582e-02  4.72889503e+02]
 [-1.80357870e-01  8.17438143e-01  1.10348708e+02]
 [-2.78248075e-04 -9.26813740e-05  1.00000000e+00]]


# Warping the source image to the destination image

## Forward warping 

In [655]:
def correct(A):
    if A[2]!=1:
        A[0] = (A[0]/A[2])
        A[1] = (A[1]/A[2])
        A[2] = (A[2]/A[2])
    return A
def round_arr(A):
    A[0]= round(A[0])
    A[1]= round(A[1])
    A[2]= round(A[2])
    return A  

In [656]:
def Get_max_min_Axis (A,B,C,D):
    
    min_x = min(A[0],B[0],C[0],D[0])
    max_x = max(A[0],B[0],C[0],D[0])
    min_y = min(A[1],B[1],C[1],D[1])
    max_y = max(A[1],B[1],C[1],D[1])
   
    return min_x , max_x , min_y , max_y

In [657]:
#### take into consideration that for homogrpahy calculations [x,y,1] is actually placed as [y,x] in the 2D matrix.
def Get_new_boundaries (h,N,M):
    A= [0,0,1]
    A_new  = np.dot(h,A)
    A_new = correct(A_new)
    A_new = round_arr(A_new)
    A_new[1] = get_coor(A_new,img1.shape[0])
    print("old value of A = ",A,"new value = ",A_new)
    B=[0,682,1]
    B_new = np.matmul(h,B )
    B_new = correct(B_new)
    B_new = round_arr(B_new)
    B_new[1] = get_coor(B_new,img1.shape[0])
    C=[1023,0,1]
    print("old value of B = ",B,"new value = ",B_new)
    C_new = np.matmul(h,C )
    C_new = correct(C_new)
    C_new = round_arr(C_new)
    C_new[1] = get_coor(C_new,img1.shape[0])
    D=[1023,682,1]
    print("old value of C= ",C,"new value = ",C_new)
    D_new = np.matmul(h,D )
    D_new = correct(D_new)
    D_new = round_arr(D_new)
    D_new[1] = get_coor(D_new,img1.shape[0])
    print("old value of D = ",D,"new value = ",D_new)
    return A_new,B_new,C_new,D_new

In [658]:
def get_coor(point,M):
    if point[1]<0:
        point[1]=0
    if point[1]>M:
        point[1]=M-1
    return point[1]
    

In [659]:
print("Fed to homography and resulted from homography:")
print('------------------------------------------------')
A,B,C,D = Get_new_boundaries(h,img2.shape[0],img2.shape[1])
# the solution is in the following format
## col, row
## x,y

Fed to homography and resulted from homography:
------------------------------------------------
old value of A =  [0, 0, 1] new value =  [473. 110.   1.]
old value of B =  [0, 682, 1] new value =  [489. 682.   1.]
old value of C=  [1023, 0, 1] new value =  [1.59e+03 0.00e+00 1.00e+00]
old value of D =  [1023, 682, 1] new value =  [1.722e+03 6.820e+02 1.000e+00]


In [660]:
min_x , max_x , min_y, max_y = Get_max_min_Axis (A,B,C,D)
print("min_y =", min_y , "max_y = ", max_y ,"min_x = ", min_x,"max_x=", max_x)

min_y = 0.0 max_y =  682.0 min_x =  473.0 max_x= 1722.0


In [661]:
new_h = int(round(abs(max_y - min_y)))
new_w = int(round(abs(max_x- min_x)))
print("The new width is (# no of columns) =",new_w)
print("The new height is (# no of rows) =",new_h)

The new width is (# no of columns) = 1249
The new height is (# no of rows) = 682


## Inverse warping

In [662]:
#compute inverse homography
h_inv = np.linalg.inv(h)
h

array([[ 6.49538139e-01, -2.14335582e-02,  4.72889503e+02],
       [-1.80357870e-01,  8.17438143e-01,  1.10348708e+02],
       [-2.78248075e-04, -9.26813740e-05,  1.00000000e+00]])

In [663]:
#convert the image to greyfor trial
gray= cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
gray_2= cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)

In [664]:
#prepare x and y arrays for interpolation
#image 2 because inverse warping is made so that we get image 2 pixel values.
x = np.arange(0, img2.shape[1], 1)
y = np.arange(0, img2.shape[0], 1)
interp_spline = RectBivariateSpline(y.reshape(-1,1), x.reshape(-1,1), gray)

In [666]:
new_img = np.zeros((img1.shape[0],new_h+img1.shape[1]))
for i in range (int(min_x),int(min_x+new_w),1):
    for j in range (int(min_y),int((min_y+new_h)),1):
        point = [i,j,1]
        co_ord = np.matmul(h_inv,point)
        co_ord = correct(co_ord)
        xi=co_ord[0]
        yi=co_ord[1]
        if (xi>=0 and yi>=0):
            intensity=int(interp_spline.ev(yi, xi))
            if(i<1706):
                 new_img[j][i] = intensity
        else:
            new_img[j][i] = 0

    

In [667]:
#show the warped image in grey scale
plt.imshow(new_img,cmap='gray')
plt.show()
#plt.close()

# Stitch the two images together

In [668]:
new_img[0:img1.shape[0],0:img1.shape[1]]= gray_2
plt.imshow(new_img,cmap='gray')
plt.show()
#plt.close()

## Test using open cv functions

In [669]:
dst = cv2.warpPerspective(img2,np.array(h),(img1.shape[1] + img2.shape[1], img1.shape[0]))
print(dst.shape)
figure(2)
plt.imshow(dst,cmap='gray')
plt.show()
plt.close()
dst[0:img1.shape[0], 0:img1.shape[1]] = img1
plt.imshow(dst,cmap='gray')
plt.show()

(683, 2048, 3)
