In [1]:
#import pacakges 
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from PIL import Image
import math
import numpy
import cv2
from pylab import *
from numpy import *
from numpy import array
import random;
from scipy.interpolate import RectBivariateSpline

# Use Sift to get matching point 

In [49]:
!pip install opencv-python==3.4.2.16
!pip install opencv-contrib-python==3.4.2.16
#!pip install opencv-python
import cv2
from PIL import Image
import numpy as np
import random
import matplotlib.pyplot as plt
img1 = cv2.imread('./Images/dest.png')
img2 = cv2.imread('./Images/src.png')
#plt.imshow(img1),plt.show(block=False)
gray= cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
gray2= cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
plt.imshow(img1),plt.show(block=False)
#plt.close()


(<matplotlib.image.AxesImage at 0x7fe7dc066a90>, None)

In [65]:
# Initiate SIFT detector
sift = cv2.xfeatures2d.SIFT_create()
kp1, src = sift.detectAndCompute(gray2,None)
kp2, dst = sift.detectAndCompute(gray,None)
print ("Found keypoints in image 2: " + str(len(kp1)))
print ("Found keypoints in image 1: " + str(len(kp2)))

Found keypoints in image 2: 227
Found keypoints in image 1: 227


In [51]:
bf = cv2.BFMatcher()
matches = bf.match(src, dst)
keypoints = [kp1,kp2]
correspondenceList = []
#matches = np.array(matches)
for match in matches:
            (x1, y1) = keypoints[0][match.queryIdx].pt
            (x2, y2) = keypoints[1][match.trainIdx].pt
            correspondenceList.append([x1, y1, x2, y2])

corrs = np.array((correspondenceList))
estimation_thresh = 0.4
print(len(corrs))

227


# Use Ransac to get the best homography

In [64]:
def ransac(corr, thresh):
    maxInliers = []
    finalH = None
    randomFour = np.zeros((4,4)) 
    for i in range(1000):
        #find 4 random points to calculate a homography
        point1 = corr[random.randrange(0, len(corr))]
        randomFour [0]=point1
        point2 = corr[random.randrange(0, len(corr))]
        randomFour [1]=point2
        point3 = corr[random.randrange(0, len(corr))]
        randomFour [2]=point3
        point4 = corr[random.randrange(0, len(corr))]
        randomFour [3]=point4

        #call the homography function on those points
        h = findHomography(randomFour)
        if h is  None:
            print("found a singular matrix but ignored it")
            continue
        else:
            inliers = []

        #for every point in the corres
            for i in range(len(corr)):
                d = geometricDistance(corr[i], h)
                if d < 5:
                    inliers.append(corr[i])

            if len(inliers) > len(maxInliers):
                maxInliers = inliers
                finalH = h
           # print ("size: ", len(corr), " NumInliers: ", len(inliers), "Max inliers: ", len(maxInliers))

            if len(maxInliers) > (len(corr)*0.4):
                break
    return finalH, maxInliers

In [10]:
def split_array(corr):
    x=[]
    y=[]
    xdash=[]
    ydash=[]
    b=[]
    for i in range(4):
        x.append(corr[i][0])
        y.append(corr[i][1])
        xdash.append(corr[i][2])
        ydash.append(corr[i][3])
        b.append(corr[i][2])
        b.append(corr[i][3])
    return x,y,xdash,ydash,b

In [11]:
def geometricDistance(correspondence, h):

    p1 = np.array([correspondence[0], correspondence[1], 1])
    estimatep2 = np.dot(h, p1)
    estimatep2 = correct(estimatep2)

    p2 = np.array([correspondence[2], correspondence[3], 1])
    error = p2 - estimatep2
    return np.linalg.norm(error)

In [12]:
def correct(A):
    if A[2]!=1:
        A[0] = (A[0]/A[2])
        A[1] = (A[1]/A[2])
        A[2] = (A[2]/A[2])
    return A
def round_arr(A):
    A[0]= round(A[0])
    A[1]= round(A[1])
    A[2]= round(A[2])
    return A  

In [13]:
def findHomography (corr):
    x,y,xdash,ydash,b = split_array(corr)
    
    M = np.array([
          [x[0],y[0],1,0,0,0,-x[0]*xdash[0], -y[0]*xdash[0]],
          [0,0,0,x[0],y[0],1,-x[0]*ydash[0], -y[0]*ydash[0]],
          [x[1],y[1],1,0,0,0,-x[1]*xdash[1],-y[1]*xdash[1]],
          [0,0,0,x[1],y[1],1,-x[1]*ydash[1],-y[1]*ydash[1]],
          [x[2],y[2],1,0,0,0,-x[2]*xdash[2],-y[2]*xdash[2]],
          [0,0,0,x[2],y[2],1,-x[2]*ydash[2],-y[2]*ydash[2]],
          [x[3],y[3],1,0,0,0,-x[3]*xdash[3],-y[3]*xdash[3]],
          [0,0,0,x[3],y[3],1,-x[3]*ydash[3],-y[3]*ydash[3]]
      ])
   # print("M = " ,M)
    try:
        a = np.dot(np.linalg.inv(M),b)
        a = np.append(a,1)
        return a.reshape(3,3)
    except:
        a = None
        return None

In [67]:
#Run the ransac
finalH, inliers = ransac(corrs, estimation_thresh)

print ("Final homography: ", finalH)
print ("Final inliers count: ", len(inliers))
h = np.array(finalH)

if len(inliers) < (0.3*len(corrs)):
    print("not optimal ")

found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
found a singular matrix but ignored it
Final homography:  [[ 5.57161750e-01  1.36759957e-01  9.65341423e+01]
 [-3.07653535e-01  8.59304968e-01  1.82426031e+01]
 [-2.16357105e-03 -2.37971860e-04  1.00000000e+00]]
Final inliers count:  66
not optimal 


# 1) Use ginput to find correspondances

In [15]:
def getPoints(image):
    img1 = Image.open(image) 
    plt.figure(1)
    plt.imshow(img1)
    print("Please click") 
    x = plt.ginput(4)
    return x

In [16]:
pts_src = getPoints('./Images/image1.jpg')
print(pts_src)
pts_dst=getPoints('./Images/image2.jpg')
print(pts_dst)
plt.close()

Please click


TclError: invalid command name "pyimage10"

In [ ]:
corrs = np.concatenate((pts_dst,pts_src),axis=1)
corrs.shape

In [ ]:
#check sizes of image one and image 2
img2 = array(Image.open('./Images/image2.jpg'))
print(img2.shape)
img1 = array(Image.open('./Images/image1.jpg'))
print (img1.shape)

#

In [ ]:
#get x,y,x',y' arrays from cores
def getArrays(src,dest):
    x=[]
    y=[]
    xdash=[]
    ydash=[]

    for i in range(4):
        x.append(src[i][0])
        y.append(src[i][1])
        xdash.append(dest[i][0])
        ydash.append(dest[i][1])

    return x,y,xdash,ydash

In [ ]:
def split_array(corr):
    x=[]
    y=[]
    xdash=[]
    ydash=[]
    b=[]
    for i in range(4):
        x.append(corr[i][0])
        y.append(corr[i][1])
        xdash.append(corr[i][2])
        ydash.append(corr[i][3])
        b.append(corr[i][2])
        b.append(corr[i][3])
    return x,y,xdash,ydash,b

In [ ]:
h=findHomography(corrs)
print("calculated homography", h)
h, status = cv2.findHomography(np.array(pts_dst),np.array(pts_src))
print("actual homogrpahy", h)

# Warping the source image to the destination image

## Forward warping 

In [68]:
def Get_max_min_Axis (A,B,C,D):
    
    min_x = min(A[0],B[0],C[0],D[0])
    max_x = max(A[0],B[0],C[0],D[0])
    min_y = min(A[1],B[1],C[1],D[1])
    max_y = max(A[1],B[1],C[1],D[1])
   
    return min_x , max_x , min_y , max_y

In [28]:
#### take into consideration that for homogrpahy calculations [x,y,1] is actually placed as [y,x] in the 2D matrix.
def Get_new_boundaries (h,N,M):
    A= [0,0,1]
    A_new  = np.dot(h,A)
    A_new = correct(A_new)
    A_new = round_arr(A_new)
    A_new[1] = get_coor(A_new,img1.shape[0])
    print("old value of A = ",A,"new value = ",A_new)
    B=[0,N-1,1]
    B_new = np.matmul(h,B )
    B_new = correct(B_new)
    B_new = round_arr(B_new)
    B_new[1] = get_coor(B_new,img1.shape[0])
    C=[M-1,0,1]
    print("old value of B = ",B,"new value = ",B_new)
    C_new = np.matmul(h,C )
    C_new = correct(C_new)
    C_new = round_arr(C_new)
    C_new[1] = get_coor(C_new,img1.shape[0])
    D=[M-1,N-1,1]
    print("old value of C= ",C,"new value = ",C_new)
    D_new = np.matmul(h,D )
    D_new = correct(D_new)
    D_new = round_arr(D_new)
    D_new[1] = get_coor(D_new,img1.shape[0])
    print("old value of D = ",D,"new value = ",D_new)
    return A_new,B_new,C_new,D_new

In [29]:
def get_coor(point,M):
    if point[1]<0:
        point[1]=0
    if point[1]>M:
        point[1]=M-1
    return point[1]
    

In [69]:
print("Fed to homography and resulted from homography:")
print('------------------------------------------------')
A,B,C,D = Get_new_boundaries(h,img2.shape[0],img2.shape[1])
# the solution is in the following format
## col, row
## x,y

Fed to homography and resulted from homography:
------------------------------------------------
old value of A =  [0, 0, 1] new value =  [97. 18.  1.]
old value of B =  [0, 136, 1] new value =  [119. 135.   1.]
old value of C=  [189, 0, 1] new value =  [341.   0.   1.]
old value of D =  [189, 136, 1] new value =  [395. 135.   1.]


In [70]:
min_x , max_x , min_y, max_y = Get_max_min_Axis (A,B,C,D)
print("min_y =", min_y , "max_y = ", max_y ,"min_x = ", min_x,"max_x=", max_x)

min_y = 0.0 max_y =  135.0 min_x =  97.0 max_x= 395.0


In [71]:
new_h = int(round(abs(max_y - min_y)))
new_w = int(round(abs(max_x- min_x)))
print("The new width is (# no of columns) =",new_w)
print("The new height is (# no of rows) =",new_h)

The new width is (# no of columns) = 298
The new height is (# no of rows) = 135


## Inverse warping

In [72]:
#compute inverse homography
h_inv = np.linalg.inv(h)
h

array([[ 5.57161750e-01,  1.36759957e-01,  9.65341423e+01],
       [-3.07653535e-01,  8.59304968e-01,  1.82426031e+01],
       [-2.16357105e-03, -2.37971860e-04,  1.00000000e+00]])

In [73]:
#convert the image to greyfor trial
gray= cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
gray_2= cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)

In [74]:
#prepare x and y arrays for interpolation
#image 2 because inverse warping is made so that we get image 2 pixel values.
x = np.arange(0, img2.shape[1], 1)
y = np.arange(0, img2.shape[0], 1)
interp_spline = RectBivariateSpline(y.reshape(-1,1), x.reshape(-1,1), gray)

In [82]:
new_img = np.zeros((img1.shape[0],new_h+img1.shape[1]))
for i in range (int(min_x),int(min_x+new_w),1):
    for j in range (int(min_y),int((min_y+new_h)),1):
        point = [i,j,1]
        co_ord = np.matmul(h_inv,point)
        co_ord = correct(co_ord)
        xi=co_ord[0]
        yi=co_ord[1]
        if (xi>=0 and yi>=0):
            intensity=int(interp_spline.ev(yi, xi))
            if(i<327):
                 new_img[j][i] = intensity
        else:
            new_img[j][i] = 0

    

In [83]:
#show the warped image in grey scale
figure(3)
plt.imshow(new_img,cmap='gray'),plt.show(block=False)
#plt.close()

(<matplotlib.image.AxesImage at 0x7fe7dc0e7dd8>, None)

# Stitch the two images together

In [79]:
new_img[0:img1.shape[0],0:img1.shape[1]]= gray_2
plt.imshow(new_img,cmap='gray')
plt.show(block=False)
#plt.close()

## Test using open cv functions

In [78]:
dst = cv2.warpPerspective(img2,np.array(h),(img1.shape[1] + img2.shape[1], img1.shape[0]))
print(dst.shape)
figure(2)
#plt.imshow(dst,cmap='gray')
#plt.show()
#plt.close()
dst[0:img1.shape[0], 0:img1.shape[1]] = img1
plt.imshow(dst,cmap='gray')
plt.show(block=False)
#plt.close()

(136, 382, 3)
