In [4]:
#import pacakges 
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from PIL import Image
import math
import numpy
from pylab import *
from numpy import *
from numpy import array
import random;
from scipy.interpolate import RectBivariateSpline
!pip install opencv-python==3.4.2.16
!pip install opencv-contrib-python==3.4.2.16
#!pip install opencv-python
import cv2
from PIL import Image
import numpy as np
import random

#  Ransac function to get the best homography

In [241]:
def ransac(corr, thresh):
    maxInliers = []
    finalH = None
    randomFour = np.zeros((4,4)) 
    for i in range(1000):
        #find 4 random points to calculate a homography
        point1 = corr[random.randrange(0, len(corr))]
        randomFour [0]=point1
        point2 = corr[random.randrange(0, len(corr))]
        randomFour [1]=point2
        point3 = corr[random.randrange(0, len(corr))]
        randomFour [2]=point3
        point4 = corr[random.randrange(0, len(corr))]
        randomFour [3]=point4

        #call the homography function on those points
        h = findHomography(randomFour)
        if h is  None:
            continue
        else:
            inliers = []

        #for every point in the corres
            for i in range(len(corr)):
                d = geometricDistance(corr[i], h)
                if d < 5:
                    inliers.append(corr[i])

            if len(inliers) > len(maxInliers):
                maxInliers = inliers
                finalH = h
           

            if len(maxInliers) > (len(corr)*0.4):
                break
    return finalH, maxInliers

In [6]:
def split_array(corr):
    x=[]
    y=[]
    xdash=[]
    ydash=[]
    b=[]
    for i in range(4):
        x.append(corr[i][0])
        y.append(corr[i][1])
        xdash.append(corr[i][2])
        ydash.append(corr[i][3])
        b.append(corr[i][2])
        b.append(corr[i][3])
    return x,y,xdash,ydash,b

In [7]:
def geometricDistance(correspondence, h):

    p1 = np.array([correspondence[0], correspondence[1], 1])
    estimatep2 = np.dot(h, p1)
    estimatep2 = correct(estimatep2)

    p2 = np.array([correspondence[2], correspondence[3], 1])
    error = p2 - estimatep2
    return np.linalg.norm(error)

In [8]:
def correct(A):
    if A[2]!=1:
        A[0] = (A[0]/A[2])
        A[1] = (A[1]/A[2])
        A[2] = (A[2]/A[2])
    return A
def round_arr(A):
    A[0]= round(A[0])
    A[1]= round(A[1])
    A[2]= round(A[2])
    return A  

In [9]:
def findHomography (corr):
    x,y,xdash,ydash,b = split_array(corr)
    
    M = np.array([
          [x[0],y[0],1,0,0,0,-x[0]*xdash[0], -y[0]*xdash[0]],
          [0,0,0,x[0],y[0],1,-x[0]*ydash[0], -y[0]*ydash[0]],
          [x[1],y[1],1,0,0,0,-x[1]*xdash[1],-y[1]*xdash[1]],
          [0,0,0,x[1],y[1],1,-x[1]*ydash[1],-y[1]*ydash[1]],
          [x[2],y[2],1,0,0,0,-x[2]*xdash[2],-y[2]*xdash[2]],
          [0,0,0,x[2],y[2],1,-x[2]*ydash[2],-y[2]*ydash[2]],
          [x[3],y[3],1,0,0,0,-x[3]*xdash[3],-y[3]*xdash[3]],
          [0,0,0,x[3],y[3],1,-x[3]*ydash[3],-y[3]*ydash[3]]
      ])
   # print("M = " ,M)
    try:
        a = np.dot(np.linalg.inv(M),b)
        a = np.append(a,1)
        return a.reshape(3,3)
    except:
        a = None
        return None

### Use ginput to find correspondances function

In [10]:
def getPoints(image):
    img1 = Image.open(image) 
    plt.figure(1)
    plt.imshow(img1)
    print("Please click") 
    x = plt.ginput(4)
    return x

# Warping the source image to the destination image

## Functions needed for warping

In [11]:
def Get_max_min_Axis (A,B,C,D):
    
    min_x = min(A[0],B[0],C[0],D[0])
    max_x = max(A[0],B[0],C[0],D[0])
    min_y = min(A[1],B[1],C[1],D[1])
    max_y = max(A[1],B[1],C[1],D[1])
   
    return min_x , max_x , min_y , max_y

In [12]:
#### take into consideration that for homogrpahy calculations [x,y,1] is actually placed as [y,x] in the 2D matrix.
def Get_new_boundaries (h,N,M):
    A= [0,0,1]
    A_new  = np.dot(h,A)
    A_new = correct(A_new)
    A_new = round_arr(A_new)
    A_new[1] = get_coor(A_new,img1.shape[0])
    print("old value of A = ",A,"new value = ",A_new)
    B=[0,N-1,1]
    B_new = np.matmul(h,B )
    B_new = correct(B_new)
    B_new = round_arr(B_new)
    B_new[1] = get_coor(B_new,img1.shape[0])
    C=[M-1,0,1]
    print("old value of B = ",B,"new value = ",B_new)
    C_new = np.matmul(h,C )
    C_new = correct(C_new)
    C_new = round_arr(C_new)
    C_new[1] = get_coor(C_new,img1.shape[0])
    D=[M-1,N-1,1]
    print("old value of C= ",C,"new value = ",C_new)
    D_new = np.matmul(h,D )
    D_new = correct(D_new)
    D_new = round_arr(D_new)
    D_new[1] = get_coor(D_new,img1.shape[0])
    print("old value of D = ",D,"new value = ",D_new)
    return A_new,B_new,C_new,D_new

In [13]:
#we limit the size of the output image height to the original images height.
def get_coor(point,M):
    if point[1]<0:
        point[1]=0
    if point[1]>M:
        point[1]=M-1
    return point[1]
    

## Inverse warping

In [349]:
def warp_image(src_img,dimensions,h_inv):
    #prepare x and y arrays for interpolation
    #image 2 because inverse warping is made so that we get image 2 pixel values.
    x = np.arange(0, src_img.shape[1], 1)
    y = np.arange(0, src_img.shape[0], 1)
    
    blue = src_img[:, :, 1] 
    green =  src_img[:, :, 2] 
    red= src_img[:, :, 3] 
    
    min_x= dimensions['min_x']
    min_y= dimensions['min_y']
    new_w= dimensions['new_w']
    new_h= dimensions['new_h']
    
    
    new_img_red= np.zeros((src_img.shape[0],new_h+src_img.shape[1]))
    new_img_blue=np.zeros((src_img.shape[0],new_h+src_img.shape[1]))
    new_img_green=np.zeros((src_img.shape[0],new_h+src_img.shape[1]))

    interp_spline_green = RectBivariateSpline(y.reshape(-1,1), x.reshape(-1,1), green)
    interp_spline_red = RectBivariateSpline(y.reshape(-1,1), x.reshape(-1,1), red)
    interp_spline_blue= RectBivariateSpline(y.reshape(-1,1), x.reshape(-1,1), blue)

    ##start warping loop
    for i in range (int(min_x),int(min_x+new_w),1):
        for j in range (int(min_y),int((min_y+new_h)),1):
            point = [i,j,1]
            co_ord = np.matmul(h_inv,point)
            co_ord = correct(co_ord)
            xi=co_ord[0]
            yi=co_ord[1]
            if (xi>=0 and yi>=0):
                if(i < new_h+src_img.shape[1]):

                    intensity=int(interp_spline_red.ev(yi, xi))
                    new_img_red[j][i] = intensity


                    intensity=int(interp_spline_blue.ev(yi, xi))
                    new_img_blue[j][i] = intensity

                    intensity=int(interp_spline_green.ev(yi, xi))
                    new_img_green[j][i] = intensity



            else:
                new_img_red[j][i] = 0
                new_img_green[j][i] = 0
                new_img_blue[j][i] = 0
                
    return new_img_red,new_img_green,new_img_blue

    

In [351]:
def form_bgr_warped_image(warped_blue,warped_red,warped_green,dimensions,src):
    rows = dimensions['rows']
    cols = dimensions['cols']
    new_h =dimensions['new_h']
    new_img = np.zeros((src.shape[0],src.shape[1]+new_h,3), 'uint8')
    new_img[:,:,0]=warped_blue
    new_img[:,:,1]=warped_green
    new_img[:,:,2]=warped_red
    
    return new_img
    

In [352]:
def perform_warping(h,src):
    
    ## check the bounding box position and size of the warped image using forward warping.
    print("Fed to homography and resulted from homography:")
    print('------------------------------------------------')
    A,B,C,D = Get_new_boundaries(h,src.shape[0],src.shape[1])

    # the solution is in the following format
    ## col, row
    ## x,y
    
    min_x , max_x , min_y, max_y = Get_max_min_Axis (A,B,C,D)
    print("min_y =", min_y , "max_y = ", max_y ,"min_x = ", min_x,"max_x=", max_x)
    
    new_h = int(round(abs(max_y - min_y)))
    new_w = int(round(abs(max_x- min_x)))
    print("The new width is (# no of columns) =",new_w)
    print("The new height is (# no of rows) =",new_h)
    
    #start by giving the the warping fns each of the following:
     ## min_x and min_y => to determine starting point of the warpd image in the dst image.
     ##new_h and new_w => to determine the size of the warped image in the dst image.
        
    dimensions = {}
    dimensions['min_x']= min_x
    dimensions['min_y'] = min_y
    dimensions['new_w']= new_w
    dimensions['new_h']=new_h

    #compute inverse homography
    h_inv = np.linalg.inv(h)

    warped_red,warped_green,warped_blue = warp_image(src,dimensions,h_inv)
    
    #initialize the new image that will sticth the two images and the merge the bgr warped channels.

    dimensions['rows'] = src.shape[0]
    dimensions['cols'] = src.shape[1]+new_h

    new_img = form_bgr_warped_image(warped_blue,warped_red,warped_green,dimensions,src)

    return new_img


    

### Stitch the two images together

In [17]:
def stitch_images(new_img,dst):
    new_img[0:dst.shape[0],0:dst.shape[1]]= dst
    return new_img
    

# Test implementation 

# *******Load the two images to be stitched*******

In [360]:
#load images 1 and 2
img1 = array(Image.open('./Images/image1.jpg')) #dest
img2 = array(Image.open('./Images/image2.jpg')) #src

gray= cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
gray2= cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)


# 1) get Homography from Ginput Corresponding

## Get matching points

In [354]:
## start by getting points from ginput()
pts_src = getPoints('./Images/image1.jpg')
print(pts_src)
pts_dst=getPoints('./Images/image2.jpg')
print(pts_dst)
plt.close()

Please click


TclError: invalid command name "pyimage698"

## Get Homography

In [355]:

corrs = np.concatenate((pts_dst,pts_src),axis=1)
 
h=findHomography(corrs)
print("calculated homography", h)

# make sure our homography matches with that of openCv
h, status = cv2.findHomography(np.array(pts_dst),np.array(pts_src))
print("actual homogrpahy", h)

#They match dudeee, duh!

calculated homography [[ 2.27730266e+00  1.15345304e+00  6.01470291e+01]
 [ 2.25000336e-01  2.24384343e+00 -2.64457084e+02]
 [ 5.91037823e-04  1.11741391e-03  1.00000000e+00]]
actual homogrpahy [[ 2.27729299e+00  1.15344274e+00  6.01499750e+01]
 [ 2.24998767e-01  2.24383255e+00 -2.64454696e+02]
 [ 5.91034072e-04  1.11740277e-03  1.00000000e+00]]


# 2) Get homography using sift only

##           Use Sift to get matching point

In [361]:
# Initiate SIFT detector
sift = cv2.xfeatures2d.SIFT_create()
kp1, src = sift.detectAndCompute(gray2,None)
kp2, dst = sift.detectAndCompute(gray,None)
print ("Found keypoints in image 2: " + str(len(kp1)))
print ("Found keypoints in image 1: " + str(len(kp2)))

Found keypoints in image 2: 4483
Found keypoints in image 1: 5778


##      Match the points using Brute-Force matcher

In [362]:
#use a mathcer to match the point the sift correspondances
bf = cv2.BFMatcher()
matches = bf.knnMatch(src,dst, k=2)
good = []
keypoints = [kp1,kp2]
for m,n in matches:
# Distance between descriptors. The lower, the better it is.
# choose desctriptors of small distances 
    if m.distance < 0.75*n.distance:
        (x1, y1) = keypoints[0][m.queryIdx].pt
        (x2, y2) = keypoints[1][m.trainIdx].pt
        good.append([x1, y1, x2, y2])

corrs= np.array((good))
len(corrs)

IndexError: list index out of range

## Choose four random points to get the homography

In [292]:
randomFour = np.zeros((4,4)) 
    #find 4 random points to calculate a homography
point1 = corrs[random.randrange(0, len(corrs))]
randomFour [0]=point1
point2 = corrs[random.randrange(0, len(corrs))]
randomFour [1]=point2
point3 = corrs[random.randrange(0, len(corrs))]
randomFour [2]=point3
point4 = corrs[random.randrange(0, len(corrs))]
randomFour [3]=point4
print(randomFour)
#call the homography function on those points
h = findHomography(randomFour)
#print(h)

[[ 72.23763275  93.29148102 181.69294739  93.00071716]
 [ 76.50997925  95.19345856 187.03327942  94.61710358]
 [ 10.39601231 111.97704315 123.96567535 117.09137726]
 [ 58.9847641   68.53914642 162.13858032  69.44406891]]


# 3) Get homography by SIFT AND RANSAC 

In [363]:
# Initiate SIFT detector
sift = cv2.xfeatures2d.SIFT_create()
kp1, src = sift.detectAndCompute(gray2,None)
kp2, dst = sift.detectAndCompute(gray,None)
print ("Found keypoints in image 2: " + str(len(kp1)))
print ("Found keypoints in image 1: " + str(len(kp2)))

Found keypoints in image 2: 4483
Found keypoints in image 1: 5778


## match the points using Brute-Force matcher

In [364]:
#use a mathcer to match the point the sift correspondances
bf = cv2.BFMatcher()
matches = bf.match(src, dst)
keypoints = [kp1,kp2]
correspondenceList = []

for match in matches:
            (x1, y1) = keypoints[0][match.queryIdx].pt
            (x2, y2) = keypoints[1][match.trainIdx].pt
            correspondenceList.append([x1, y1, x2, y2])

corrs = np.array((correspondenceList))
estimation_thresh = 0.4
print(len(corrs))

4483


## Run ransac to get the optimal Homography

In [365]:
#Run the ransac
h, inliers = ransac(corrs, estimation_thresh)

print ("Final homography: ", h)
print ("Final inliers count: ", len(inliers))
h = np.array(h)

if len(inliers) < (0.4*len(corrs)):
    print("not optimal ")

/home/fatma/anaconda3/envs/grad/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until
/home/fatma/anaconda3/envs/grad/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  after removing the cwd from sys.path.
/home/fatma/anaconda3/envs/grad/lib/python3.6/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in double_scalars
  """


Final homography:  [[ 7.66488599e-01  2.79732156e-02  4.50961475e+02]
 [-1.37261581e-01  9.15973047e-01  7.56147384e+01]
 [-2.11197729e-04 -2.98989905e-05  1.00000000e+00]]
Final inliers count:  1187
not optimal 


## Perform Warping

In [348]:

new_img = perform_warping(h,img2)

#plot the warped image
figure(2)
plt.imshow(new_img)
plt.show(block=False)
#plt.close()

Fed to homography and resulted from homography:
------------------------------------------------
old value of A =  [0, 0, 1] new value =  [-185.    0.    1.]
old value of B =  [0, 373, 1] new value =  [-186.  291.    1.]
old value of C=  [516, 0, 1] new value =  [345.   0.   1.]
old value of D =  [516, 373, 1] new value =  [205. 369.   1.]
min_y = 0.0 max_y =  369.0 min_x =  -186.0 max_x= 345.0
The new width is (# no of columns) = 531
The new height is (# no of rows) = 369


## Stitch the two images together.

In [328]:
new_img= stitch_images(new_img,img1)
figure ('ours')
#plot the final stitched image.
plt.imshow(new_img)
plt.show(block =False)
#plt.close()

# Test using open cv functions

In [329]:
dst = cv2.warpPerspective(img2,np.array(h),(img1.shape[1] + img2.shape[1], img1.shape[0]))

##plot the warped imageby open cv fn
figure('opencv')
plt.imshow(dst)
plt.show(block=False)
#plt.close()

#plot the final stitched image by openCv
dst[0:img1.shape[0], 0:img1.shape[1]] = img1
plt.imshow(dst,cmap='gray')
plt.show(block= False)
#plt.close()

#Viola! they match :D