In [3]:
#import pacakges 
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from PIL import Image
import math
import numpy
import cv2
from pylab import *
from numpy import *
from numpy import array
import random;
from scipy.interpolate import RectBivariateSpline

# Use Sift to get matching point 

In [ ]:
!pip install opencv-python==3.4.2.16
!pip install opencv-contrib-python==3.4.2.16
#!pip install opencv-python
import cv2
from PIL import Image
import numpy as np
import random
import matplotlib.pyplot as plt
img1 = cv2.imread('./Images/dest.png')
img2 = cv2.imread('./Images/src.png')
#plt.imshow(img1),plt.show(block=False)
gray= cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
gray2= cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
plt.imshow(img1),plt.show(block=False)
#plt.close()


In [ ]:
# Initiate SIFT detector
sift = cv2.xfeatures2d.SIFT_create()
kp1, src = sift.detectAndCompute(gray2,None)
kp2, dst = sift.detectAndCompute(gray,None)
print ("Found keypoints in image 2: " + str(len(kp1)))
print ("Found keypoints in image 1: " + str(len(kp2)))

In [ ]:
bf = cv2.BFMatcher()
matches = bf.match(src, dst)
keypoints = [kp1,kp2]
correspondenceList = []
#matches = np.array(matches)
for match in matches:
            (x1, y1) = keypoints[0][match.queryIdx].pt
            (x2, y2) = keypoints[1][match.trainIdx].pt
            correspondenceList.append([x1, y1, x2, y2])

corrs = np.array((correspondenceList))
estimation_thresh = 0.4
print(len(corrs))

#  Ransac function to get the best homography

In [ ]:
def ransac(corr, thresh):
    maxInliers = []
    finalH = None
    randomFour = np.zeros((4,4)) 
    for i in range(1000):
        #find 4 random points to calculate a homography
        point1 = corr[random.randrange(0, len(corr))]
        randomFour [0]=point1
        point2 = corr[random.randrange(0, len(corr))]
        randomFour [1]=point2
        point3 = corr[random.randrange(0, len(corr))]
        randomFour [2]=point3
        point4 = corr[random.randrange(0, len(corr))]
        randomFour [3]=point4

        #call the homography function on those points
        h = findHomography(randomFour)
        if h is  None:
            print("found a singular matrix but ignored it")
            continue
        else:
            inliers = []

        #for every point in the corres
            for i in range(len(corr)):
                d = geometricDistance(corr[i], h)
                if d < 5:
                    inliers.append(corr[i])

            if len(inliers) > len(maxInliers):
                maxInliers = inliers
                finalH = h
           # print ("size: ", len(corr), " NumInliers: ", len(inliers), "Max inliers: ", len(maxInliers))

            if len(maxInliers) > (len(corr)*0.4):
                break
    return finalH, maxInliers

In [4]:
def split_array(corr):
    x=[]
    y=[]
    xdash=[]
    ydash=[]
    b=[]
    for i in range(4):
        x.append(corr[i][0])
        y.append(corr[i][1])
        xdash.append(corr[i][2])
        ydash.append(corr[i][3])
        b.append(corr[i][2])
        b.append(corr[i][3])
    return x,y,xdash,ydash,b

In [ ]:
def geometricDistance(correspondence, h):

    p1 = np.array([correspondence[0], correspondence[1], 1])
    estimatep2 = np.dot(h, p1)
    estimatep2 = correct(estimatep2)

    p2 = np.array([correspondence[2], correspondence[3], 1])
    error = p2 - estimatep2
    return np.linalg.norm(error)

In [6]:
def correct(A):
    if A[2]!=1:
        A[0] = (A[0]/A[2])
        A[1] = (A[1]/A[2])
        A[2] = (A[2]/A[2])
    return A
def round_arr(A):
    A[0]= round(A[0])
    A[1]= round(A[1])
    A[2]= round(A[2])
    return A  

In [5]:
def findHomography (corr):
    x,y,xdash,ydash,b = split_array(corr)
    
    M = np.array([
          [x[0],y[0],1,0,0,0,-x[0]*xdash[0], -y[0]*xdash[0]],
          [0,0,0,x[0],y[0],1,-x[0]*ydash[0], -y[0]*ydash[0]],
          [x[1],y[1],1,0,0,0,-x[1]*xdash[1],-y[1]*xdash[1]],
          [0,0,0,x[1],y[1],1,-x[1]*ydash[1],-y[1]*ydash[1]],
          [x[2],y[2],1,0,0,0,-x[2]*xdash[2],-y[2]*xdash[2]],
          [0,0,0,x[2],y[2],1,-x[2]*ydash[2],-y[2]*ydash[2]],
          [x[3],y[3],1,0,0,0,-x[3]*xdash[3],-y[3]*xdash[3]],
          [0,0,0,x[3],y[3],1,-x[3]*ydash[3],-y[3]*ydash[3]]
      ])
   # print("M = " ,M)
    try:
        a = np.dot(np.linalg.inv(M),b)
        a = np.append(a,1)
        return a.reshape(3,3)
    except:
        a = None
        return None

In [ ]:
#Run the ransac
finalH, inliers = ransac(corrs, estimation_thresh)

print ("Final homography: ", finalH)
print ("Final inliers count: ", len(inliers))
h = np.array(finalH)

if len(inliers) < (0.3*len(corrs)):
    print("not optimal ")

# 1) Use ginput to find correspondances

In [54]:
def getPoints(image):
    img1 = Image.open(image) 
    plt.figure(1)
    plt.imshow(img1)
    print("Please click") 
    x = plt.ginput(4)
    return x

# Warping the source image to the destination image

## Functions needed for warping

In [58]:
def Get_max_min_Axis (A,B,C,D):
    
    min_x = min(A[0],B[0],C[0],D[0])
    max_x = max(A[0],B[0],C[0],D[0])
    min_y = min(A[1],B[1],C[1],D[1])
    max_y = max(A[1],B[1],C[1],D[1])
   
    return min_x , max_x , min_y , max_y

In [59]:
#### take into consideration that for homogrpahy calculations [x,y,1] is actually placed as [y,x] in the 2D matrix.
def Get_new_boundaries (h,N,M):
    A= [0,0,1]
    A_new  = np.dot(h,A)
    A_new = correct(A_new)
    A_new = round_arr(A_new)
    A_new[1] = get_coor(A_new,img1.shape[0])
    print("old value of A = ",A,"new value = ",A_new)
    B=[0,N-1,1]
    B_new = np.matmul(h,B )
    B_new = correct(B_new)
    B_new = round_arr(B_new)
    B_new[1] = get_coor(B_new,img1.shape[0])
    C=[M-1,0,1]
    print("old value of B = ",B,"new value = ",B_new)
    C_new = np.matmul(h,C )
    C_new = correct(C_new)
    C_new = round_arr(C_new)
    C_new[1] = get_coor(C_new,img1.shape[0])
    D=[M-1,N-1,1]
    print("old value of C= ",C,"new value = ",C_new)
    D_new = np.matmul(h,D )
    D_new = correct(D_new)
    D_new = round_arr(D_new)
    D_new[1] = get_coor(D_new,img1.shape[0])
    print("old value of D = ",D,"new value = ",D_new)
    return A_new,B_new,C_new,D_new

In [60]:
#we limit the size of the output image height to the original images height.
def get_coor(point,M):
    if point[1]<0:
        point[1]=0
    if point[1]>M:
        point[1]=M-1
    return point[1]
    

## Inverse warping

In [73]:
def warp_image(src_img,new_borders,h_inv):
    #prepare x and y arrays for interpolation
    #image 2 because inverse warping is made so that we get image 2 pixel values.
    x = np.arange(0, src_img.shape[1], 1)
    y = np.arange(0, src_img.shape[0], 1)
    
    blue = src_img[:, :, 0] 
    green =  src_img[:, :, 1] 
    red= src_img[:, :, 2] 
    
    min_x= dimensions['min_x']
    min_y= dimensions['min_y']
    new_w= dimensions['new_w']
    new_h= dimensions['new_h']
    
    
    new_img_red= np.zeros((src_img.shape[0],new_h+src_img.shape[1]))
    new_img_blue=np.zeros((src_img.shape[0],new_h+src_img.shape[1]))
    new_img_green=np.zeros((src_img.shape[0],new_h+src_img.shape[1]))

    interp_spline_green = RectBivariateSpline(y.reshape(-1,1), x.reshape(-1,1), green)
    interp_spline_red = RectBivariateSpline(y.reshape(-1,1), x.reshape(-1,1), red)
    interp_spline_blue= RectBivariateSpline(y.reshape(-1,1), x.reshape(-1,1), blue)

    ##start warping loop
    for i in range (int(min_x),int(min_x+new_w),1):
        for j in range (int(min_y),int((min_y+new_h)),1):
            point = [i,j,1]
            co_ord = np.matmul(h_inv,point)
            co_ord = correct(co_ord)
            xi=co_ord[0]
            yi=co_ord[1]
            if (xi>=0 and yi>=0):
                if(i < 1706):

                    intensity=int(interp_spline_red.ev(yi, xi))
                    new_img_red[j][i] = intensity


                    intensity=int(interp_spline_blue.ev(yi, xi))
                    new_img_blue[j][i] = intensity

                    intensity=int(interp_spline_green.ev(yi, xi))
                    new_img_green[j][i] = intensity



            else:
                new_img_red[j][i] = 0
                new_img_green[j][i] = 0
                new_img_blue[j][i] = 0
                
    return new_img_red,new_img_green,new_img_blue

    

In [62]:
def form_bgr_warped_image(warped_blue,warped_red,warped_green,dimensions):
    rows = dimensions['rows']
    cols = dimensions['cols']
    new_img = np.zeros((img2.shape[0],img2.shape[1]+new_h,3), 'uint8')
    new_img[:,:,0]=new_img_blue
    new_img[:,:,1]=new_img_green
    new_img[:,:,2]=new_img_red
    return new_img
    

## Stitch the two images together

In [63]:
def stitch_images(new_img,dst):
    new_img[0:dst.shape[0],0:dst.shape[1]]= dst
    return new_img
    

# Test implementation

In [ ]:
## start by getting points from ginput()
pts_src = getPoints('./Images/image1.jpg')
print(pts_src)
pts_dst=getPoints('./Images/image2.jpg')
print(pts_dst)
plt.close()

In [79]:

corrs = np.concatenate((pts_dst,pts_src),axis=1)

h=findHomography(corrs)
print("calculated homography", h)

# make sure our homography matches with that of openCv
h, status = cv2.findHomography(np.array(pts_dst),np.array(pts_src))
print("actual homogrpahy", h)

#They match dudeee, duh!

calculated homography [[ 6.08782644e-01 -8.10056669e-02  4.91689271e+02]
 [-1.41284123e-01  7.92295622e-01  9.14988372e+01]
 [-2.80762963e-04 -1.55009331e-04  1.00000000e+00]]
actual homogrpahy [[ 6.08782088e-01 -8.10062410e-02  4.91689528e+02]
 [-1.41284193e-01  7.92295241e-01  9.14989187e+01]
 [-2.80763095e-04 -1.55009774e-04  1.00000000e+00]]


In [64]:
#check sizes of image one and image 2
img2 = array(Image.open('./Images/image2.jpg'))
print(img2.shape)
img1 = array(Image.open('./Images/image1.jpg'))
print (img1.shape)

(683, 1024, 3)
(683, 1024, 3)


In [65]:
## check the bounding box position and size of the warped image using forward warping.
print("Fed to homography and resulted from homography:")
print('------------------------------------------------')
A,B,C,D = Get_new_boundaries(h,img2.shape[0],img2.shape[1])

# the solution is in the following format
## col, row
## x,y

Fed to homography and resulted from homography:
------------------------------------------------
old value of A =  [0, 0, 1] new value =  [492.  91.   1.]
old value of B =  [0, 682, 1] new value =  [488. 682.   1.]
old value of C=  [1023, 0, 1] new value =  [1.564e+03 0.000e+00 1.000e+00]
old value of D =  [1023, 682, 1] new value =  [1.745e+03 6.820e+02 1.000e+00]


In [66]:
min_x , max_x , min_y, max_y = Get_max_min_Axis (A,B,C,D)
print("min_y =", min_y , "max_y = ", max_y ,"min_x = ", min_x,"max_x=", max_x)

min_y = 0.0 max_y =  682.0 min_x =  488.0 max_x= 1745.0


In [67]:
new_h = int(round(abs(max_y - min_y)))
new_w = int(round(abs(max_x- min_x)))
print("The new width is (# no of columns) =",new_w)
print("The new height is (# no of rows) =",new_h)

The new width is (# no of columns) = 1257
The new height is (# no of rows) = 682


In [74]:
#start by giving the the warping fns each of the following:
     ## min_x and min_y => to determine starting point of the warpd image in the dst image.
     ##new_h and new_w => to determine the size of the warped image in the dst image.
        
dimensions = {}
dimensions['min_x']= min_x
dimensions['min_y'] = min_y
dimensions['new_w']= new_w
dimensions['new_h']=new_h

#compute inverse homography
h_inv = np.linalg.inv(h)

warped_red,warped_green,warped_blue = warp_image(img2,dimensions,h_inv)

In [75]:
#initialize the new image that will sticth the two images and the merge the bgr warped channels.

dimensions['rows'] = img2.shape[0]
dimensions['cols'] = img2.shape[1]+new_h

new_img = form_bgr_warped_image(warped_blue,warped_red,warped_green,dimensions)

#plot the warped image
figure(2)
plt.imshow(new_img)
plt.show()
plt.close()

In [76]:
new_img= stitch_images(new_img,img1)
#plot the final stitched image.
plt.imshow(new_img)
plt.show()
plt.close()

### Test using open cv functions

In [ ]:
dst = cv2.warpPerspective(img2,np.array(h),(img1.shape[1] + img2.shape[1], img1.shape[0]))

##plot the warped imageby open cv fn
figure(2)
plt.imshow(dst)
plt.show()
plt.close()

#plot the final stitched image by openCv
dst[0:img1.shape[0], 0:img1.shape[1]] = img1
plt.imshow(dst,cmap='gray')
plt.show()
plt.close()

#Viola! they match :D